### PR TITLE
Add DateSelectComponent

### PR DESCRIPTION
**Pull request by Malian**
This PR aims to add a `DateSelectComponent` that is a wrapper for Phoenix.HTML.Form's `date_select/3` function

- [x] Create component
- [x] Test
- [x] Doc
- [x] Parse "class" option of each select to allow the use of `"my-class": true` format
- [ ] ~Maybe update other select component to respect the new standard way to write Surface Form component.~

### CODE REVIEW

**Comment by Malian** [comment]
Ready to review

I am not sure about the way I handle the "css_class" of underlying selects.

I propose to move the "update other select component to respect the new standard way to write Surface Form component" to an other pull request.

**Review by msaraiva — COMMENTED** [review]
@Malian looks good. I left just a couple of nitpicks for your consideration.

By _"Maybe update other select component to respect the new standard way to write Surface Form component"_ do you mean only the `DateTimeSelect`? If so, yes. We should add `:default`, and all the `year`, `month`, `day`, etc. options to keep them consistent. But it can be certainly done in a separate PR.

Thanks!

**Comment by Malian** [comment]
> We should add `:default`, and all the `year`, `month`, `day`, etc. options to keep them consistent. But it can be certainly done in a separate PR.

Yes, I was referring to `DateTimeSelect` and `TimeSelect`. I'll modify these components in another pull request.

**Comment by msaraiva** [comment]
@Malian thanks! ❤️

**Pull request merged**
