### PR TITLE
Specify a live view version

### PR DESCRIPTION
**Pull request by brainlid**
Don't directly track phoenix_live_view master branch.

Specify dependency on 0.7.0 (latest released live view version)

This helps solve the problem of using surface in the project causes the whole project to be tied to the active development of live view master.

### CODE REVIEW

**Comment by cadebward** [comment]
>  0.6.0 (latest released live view version)

haha thats so three hours ago!

**Comment by emeidell** [comment]
Common @brainlid can you be more on top of this? 😉

**Comment by brainlid** [comment]
@cadebward Ha! Hitting a fast moving target is hard! :dart: Updated to move to 0.7.0. All tests still pass

**Comment by msaraiva** [comment]
Thanks! ❤️

**Pull request merged**
